// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/calisan/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/[id].put').default>>>>
    }
    '/api/calisan/excel': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/excel').default>>>>
    }
    '/api/calisan/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/get').default>>>>
    }
    '/api/calisan/getByFirmaId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/getByFirmaId').default>>>>
    }
    '/api/calisan/getByYerleskeId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/getByYerleskeId').default>>>>
    }
    '/api/calisan/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calisan/post').default>>>>
    }
    '/api/dokuman/yukle': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dokuman/yukle').default>>>>
    }
    '/api/egitim/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/[id].put').default>>>>
    }
    '/api/egitim/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/get').default>>>>
    }
    '/api/egitim/getByCalisanId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/getByCalisanId').default>>>>
    }
    '/api/egitim/getByFirmaId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/getByFirmaId').default>>>>
    }
    '/api/egitim/getGroupedByKategori': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/getGroupedByKategori').default>>>>
    }
    '/api/egitim/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitim/post').default>>>>
    }
    '/api/egitimkonu/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitimkonu/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitimkonu/[id].put').default>>>>
    }
    '/api/egitimkonu/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitimkonu/get').default>>>>
    }
    '/api/egitimkonu/getByKategoriId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitimkonu/getByKategoriId').default>>>>
    }
    '/api/egitimkonu/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/egitimkonu/post').default>>>>
    }
    '/api/evrak/delete/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/evrak/delete/[id]').default>>>>
    }
    '/api/evrak/download': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/evrak/download').default>>>>
    }
    '/api/evrak/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/evrak/get').default>>>>
    }
    '/api/evrak/upload': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/evrak/upload').default>>>>
    }
    '/api/firma/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/[id].put').default>>>>
    }
    '/api/firma/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/get').default>>>>
    }
    '/api/firma/getLatestFirmaKodu': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/getLatestFirmaKodu').default>>>>
    }
    '/api/firma/nace-search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/nace-search').default>>>>
    }
    '/api/firma/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firma/post').default>>>>
    }
    '/api/firmaevrak/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/firmaevrak/get').default>>>>
    }
    '/api/kategori/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori/get').default>>>>
    }
    '/api/kategori/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori/post').default>>>>
    }
    '/api/yerleske/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yerleske/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yerleske/[id].put').default>>>>
    }
    '/api/yerleske/get': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yerleske/get').default>>>>
    }
    '/api/yerleske/getByFirmaId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yerleske/getByFirmaId').default>>>>
    }
    '/api/yerleske/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yerleske/post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}