// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04.04.2025 13:50:54
const configMerger = require("D:/WEB_PROJELER/isg-programi/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/WEB_PROJELER/isg-programi/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/plugins/**/*.{js,ts,mjs}","D:/WEB_PROJELER/isg-programi/composables/**/*.{js,ts,mjs}","D:/WEB_PROJELER/isg-programi/utils/**/*.{js,ts,mjs}","D:/WEB_PROJELER/isg-programi/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/WEB_PROJELER/isg-programi/app.config.{js,ts,mjs}"] } }));

module.exports = config
